sudo: required
dist: trusty
language: node

before_script:
  # install v6.x of nodejs
   - nvm install 10.11
  #install yarn globally
   - npm install -g yarn

script:
  - yarn install
  - yarn purs:install
  - yarn purs:build
  - yarn test
